### ISSUE TITLE
Where's scale_fill_colorplane?

### ISSUE THREAD

**Issue by RenatoPdosSantos** [wmurphyrd/colorplaner#22] opened 2016-08-30 07:51 UTC
Hi!

This package promises to be great!

I succeeded installing with no problems or warnings, but yet I get the message
Error: could not find function "scale_fill_colorplane"

**Comment by wmurphyrd** [comment] 2016-08-30 17:04
Thanks for your interest in the package! 

Could you provide a reproducible example for the error? 

I was not able to reproduce it with a basic test:

```R
library(colorplaner)
ggplot(mtcars, aes(x = wt, y = mpg, fill = disp, fill2 = hp)) +
      geom_point(shape = 23, size = 5) +
      scale_fill_colorplane()
```

Will that code run for you?

**Comment by RenatoPdosSantos** [comment] 2016-08-30 17:58
That's weird!
Your code run smoothly.
And after I copied the function name from your code and pasted into mine it ran as well!
I definitely must have made a typo.
This package is great, indeed! It saved my project.
My deepest apologies.

**Comment by wmurphyrd** [comment] 2016-08-31 02:01
I'll close this for now, but let me know if it happens again. Also, I'd love to see how you've used colorplaner if you can share.

**Closed by wmurphyrd** 2016-08-31 02:01 UTC
